### ISSUE TITLE
Fedora Rawhide CI jobs failing

### ISSUE THREAD

**Issue by platisd** [ItJustWorksTM/libSMCE#28]
Forked the repo to try some stuff out and found out that there are [two jobs failing on CI](https://github.com/platisd/libSMCE/actions/runs/1100900374).

**Comment by AeroStun** [comment]
The failures on Fedora Rawhide and OpenMandriva Lx Cooker appear to be due to a bug in libcurl as well as a bug in Docker (which could be worked around if the CI runner hosts didn't use ancient Linux kernel versions)

Those jobs have been disabled in 18178dbf , until patches either get backported or software versions become stable.
